id: P000203
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །བགྲོད་བྱ་ས་དང་ལམ་གྱི་རིམ་པ་ཕྱེ་བ། །
  authors: []
  layers:
  - book_title
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: RDI-TOK-09-1
web_metadata:
  title:
    en: An Analysis of the Paths and Levels to Be Traversed
    bo: འགྲོད་བྱ་ས་དང་ལམ་གྱི་རིམ་པར་ཕྱེ་བ།
  collection:
    en: Treasury of Knowledge–  Book 9
    bo: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད།–  དེབ། ༩
  author:
    en: Jamgon Kongtrul Lodro Thaye
    bo: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-TOK-09-1
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-TOK-09-1.epub
  description:
    en: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད། གནས་དགུ་པ།
    bo: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད། གནས་དགུ་པ།
